name: Deploy Web to GitHub Pages
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter create --org com.example template_app
      - run: cp lib/main.dart template_app/lib/main.dart
      
      - name: Install dependencies
        run: |
          cd template_app
          flutter pub add google_fonts cupertino_icons
          
      # Собираем Web-версию с правильным указанием пути к вашему репозиторию
      - name: Build Web
        run: |
          cd template_app
          flutter build web --release --base-href "/${{ github.event.repository.name }}/"
          
      # Публикуем готовый сайт прямо в репозиторий
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: template_app/build/web
          branch: gh-pages

